version: "3"
services:
  influxdb:
    image: influxdb:1.3.4-alpine
    ports:
      - "8086:8086"
    networks:
      - influx
  chronograf:
    image: chronograf:1.3.6.1-alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086/
    ports:
      - "8888:8888"
    networks:
      - influx
  telegraf:
    image: telegraf:1.3.5-alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influx
networks:
  influx: